### ISSUE TITLE
TELEGRAPH_ACCS

### ISSUE THREAD

**Issue by Rebaxa007** [l3v11/SearchX#11]
What is TELEGRAPH_ACCS can ypu please explain and how to get it.

**Comment by l3v11** [comment]
@Rebaxa007 set this
TELEGRAPH_ACCS=2

**Comment by Rebaxa007** [comment]
> @Rebaxa007 set this TELEGRAPH_ACCS=2
My heroku account suspended any fix for this to avoid suspension

**Comment by l3v11** [comment]
Contact heroku support
