### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by ronin08** [l3v11/SearchX#15]
Add /unzipmirror command to unzip/extract .zip, .rar or other compressed files directly from drive link , gdtot links, etc.

**Comment by EmilyMirror** [comment]
@ronin08 Bro This is not a Mirror Bot. It is a Multi Purpose GDrive Search Bot.

**Comment by l3v11** [comment]
@ronin08 check this out https://github.com/l3v11/SearchX/commit/547f6c96614bb7f274d4e6d15cfb80eb3c6f3338

**Comment by ronin08** [comment]
Thank you so much!
will it extract directly from gdtot link?

**Comment by l3v11** [comment]
> Thank you so much! will it extract directly from gdtot link?

Welcome. Yes, it'll extract directly from gdtot if it's an archived file.

**Comment by ronin08** [comment]
🤩👏
