### ISSUE TITLE
APPDRIVE details in config.env

### ISSUE THREAD

**Issue by Telestosatt** [l3v11/SearchX#16]
How to fill below details in config.env if we using google+ login in appdrive?
```
APPDRIVE_EMAIL=
APPDRIVE_PASS=
```
As its a google+ login, we have to fill google login password?

**Comment by l3v11** [comment]
@Telestosatt 
You can add password on your account after logging in with google

**Comment by Telestosatt** [comment]
> 

ooh ok
never knew this lol
I Always just logged in, cloned files needed and logged out. Then I went to my google account and revoke appdrive authorization  😂🙂

Thank you for info

**Comment by l3v11** [comment]
Ohh you're welcome
